version: "3"

services:
  db:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: sa
  app:
    build: .
    container_name: rest-service
    ports:
      - "80:8080"
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
    depends_on:
      - db
    env_file:
      - .env.dev
    
