version: "3"

services:
  db:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: sa
  app:
    build: .
    container_name: rest-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    
